"""step2_product_master_enhancements

Revision ID: 119ca9cccff9
Revises: e1b4d8a2c6f3
Create Date: 2026-08-04 12:59:06.090624

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '119ca9cccff9'
down_revision = 'e1b4d8a2c6f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply this migration's schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_employees_phone', table_name='employees')
    op.create_unique_constraint(None, 'employees', ['phone'])
    op.add_column('hsn_codes', sa.Column('refund_vat_percent', sa.Numeric(precision=5, scale=2), nullable=False))
    op.add_column('products', sa.Column('product_name_tally', sa.String(length=255), nullable=False))
    op.add_column('products', sa.Column('product_name_invoice', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('refund_vat_percent', sa.Numeric(precision=5, scale=2), nullable=False))
    op.add_column('products', sa.Column('license_certificate_required', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('packaging_quantity', sa.Numeric(precision=12, scale=3), nullable=True))
    op.add_column('products', sa.Column('packaging_net_weight', sa.Numeric(precision=12, scale=3), nullable=True))
    op.add_column('products', sa.Column('packaging_gross_weight', sa.Numeric(precision=12, scale=3), nullable=True))
    op.add_column('products', sa.Column('length_cm', sa.Numeric(precision=12, scale=3), nullable=True))
    op.add_column('products', sa.Column('width_cm', sa.Numeric(precision=12, scale=3), nullable=True))
    op.add_column('products', sa.Column('height_cm', sa.Numeric(precision=12, scale=3), nullable=True))
    op.add_column('products', sa.Column('packaging_unit_cbm', sa.Numeric(precision=12, scale=6), nullable=True))
    op.add_column('products', sa.Column('current_stock', sa.Numeric(precision=14, scale=3), nullable=False))
    op.create_index(op.f('ix_products_product_name_tally'), 'products', ['product_name_tally'], unique=False)
    op.alter_column('queue_jobs', 'priority',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('queue_jobs', 'run_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('queue_jobs', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('queue_jobs', 'retry_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('queue_jobs', 'max_retries',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('supplier_category_links', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('supplier_sub_category_links', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration's schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('supplier_sub_category_links', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('supplier_category_links', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('queue_jobs', 'max_retries',
               existing_type=sa.INTEGER(),
               server_default=sa.text('3'),
               existing_nullable=False)
    op.alter_column('queue_jobs', 'retry_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('queue_jobs', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'PENDING'::character varying"),
               existing_nullable=False)
    op.alter_column('queue_jobs', 'run_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('queue_jobs', 'priority',
               existing_type=sa.INTEGER(),
               server_default=sa.text('5'),
               existing_nullable=False)
    op.drop_index(op.f('ix_products_product_name_tally'), table_name='products')
    op.drop_column('products', 'current_stock')
    op.drop_column('products', 'packaging_unit_cbm')
    op.drop_column('products', 'height_cm')
    op.drop_column('products', 'width_cm')
    op.drop_column('products', 'length_cm')
    op.drop_column('products', 'packaging_gross_weight')
    op.drop_column('products', 'packaging_net_weight')
    op.drop_column('products', 'packaging_quantity')
    op.drop_column('products', 'license_certificate_required')
    op.drop_column('products', 'refund_vat_percent')
    op.drop_column('products', 'product_name_invoice')
    op.drop_column('products', 'product_name_tally')
    op.drop_column('hsn_codes', 'refund_vat_percent')
    op.drop_constraint(None, 'employees', type_='unique')
    op.create_index('ix_employees_phone', 'employees', ['phone'], unique=True)
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    # ### end Alembic commands ###
